<?php

/**
 * BaseHouse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idhouses
 * @property string $name
 * @property integer $region
 * @property string $city
 * @property string $zipCode
 * @property string $street
 * @property string $tel
 * @property string $email
 * @property string $www
 * @property string $slogan
 * @property tinyint $target
 * @property Region $Region
 * @property Package $Package
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHouse extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('houses');
        $this->hasColumn('idhouses', 'integer', null, array(
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('region', 'integer', null, array(
             'unsigned' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('zipCode', 'string', 6, array(
             'type' => 'string',
             'length' => '6',
             ));
        $this->hasColumn('street', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('tel', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('www', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('slogan', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('target', 'tinyint', 1, array(
             'type' => 'tinyint',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region', array(
             'local' => 'region',
             'foreign' => 'idregions'));

        $this->hasOne('Package', array(
             'local' => 'idhouses',
             'foreign' => 'recipient'));
    }
}