<?php

/**
 * BasePackage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idpackages
 * @property integer $recipient
 * @property integer $letter
 * @property tinyint $status
 * @property House $House
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePackage extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('packages');
        $this->hasColumn('idpackages', 'integer', null, array(
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('recipient', 'integer', null, array(
             'unsigned' => true,
             'notnull' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('letter', 'integer', null, array(
             'unsigned' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'tinyint', null, array(
             'type' => 'tinyint',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('House', array(
             'local' => 'recipient',
             'foreign' => 'idhouses'));
    }
}