<?php

/**
 * HouseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HouseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HouseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('House');
    }
}